name: Build
run-name: Build ${{ inputs.image_id }}

on:
  workflow_dispatch:
    inputs:
      image_id:
        required: true
        type: string
  workflow_call:
    inputs:
      image_id:
        required: true
        type: string
    outputs:
      ami_name:
        description: "The name of the built AMI"
        value: ${{ jobs.build.outputs.ami_name }}
      ami_id:
        description: "The ID of the built AMI"
        value: ${{ jobs.build.outputs.ami_id }}

jobs:
  build:
    name: Build ${{ inputs.image_id }}
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
    env:
      SUBNET_ID: ${{ secrets.SUBNET_ID }}
    outputs:
      ami_name: ${{ steps.build.outputs.ami_name }}
      ami_id: ${{ steps.build.outputs.ami_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - run: git log --oneline -n 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.RUNS_ON_AWS_REGION }}
      - run: bundle exec bin/build --image-id ${{ inputs.image_id }}
        id: build
        timeout-minutes: 300