name: Cleanup production AMIs

concurrency:
  group: cleanup

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 2 * * *'

jobs:
  cleanup:
    timeout-minutes: 30
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=2cpu-linux-x64
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.RUNS_ON_AWS_REGION }}
      - run: bundle exec bin/utils/cleanup-amis -f
        env:
          AMI_PREFIX: runs-on-v2.2
