name: Test
run-name: Test ${{ inputs.ami_id }}

on:
  workflow_dispatch:
    inputs:
      ami_id:
        required: true
        type: string
  workflow_call:
    inputs:
      ami_id:
        required: true
        type: string
      index:
        required: true
        type: number

jobs:
  test:
    name: Test${{ inputs.index || '1' }}
    runs-on:
      - runs-on
      - family=g4dn.xlarge
      - ami=${{ inputs.ami_id }}
    steps:
      - name: Logs
        run: sudo cat /var/log/cloud-init-output.log
      - name: Systemctl status
        run: sudo systemctl status
      - name: Disk
        run: |
          sudo df -ah
          sudo lsblk -l
      - name: env
        run: env | sort
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker
        run: docker run hello-world
      - name: envinfo
        run: npx envinfo
      - name: env
        run: env | sort
      - name: show HOME
        run: ls -al $HOME
      - name: rustup
        run: rustup --version
      - name: Do something
        run: |
          echo "Hello world from $HOSTNAME"
